apiVersion: fastdfs.beordie.cn/v1
kind: FastDFS
metadata:
  labels:
    app.kubernetes.io/name: fastdfs
    app.kubernetes.io/instance: fastdfs-sample
    app.kubernetes.io/part-of: fastdfs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fastdfs
  name: fastdfs-sample
spec:
  # TODO(user): Add fields here
  replicas: 1
  participantReplicas: 1
  version: 2.11.0
  labels:
    cloud.netease.com/app: fastdfs
  pod:
    imagePullPolicy: IfNotPresent
    imagePullRepository: luhuiguo
    image:
      name: fastdfs
      version: latest
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 100Mi
  storage:
    diskSize: 2
    reclaimPolicy: Delete
    storageClass: local-storage
    unit: Gi
