apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/k8s
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: pvc
              operator: In
              values:
                - local